### PR TITLE
It doesn't compile for me without these fixes

### PR DESCRIPTION
**Pull request by moonshadow565**
Include fixes should be merged for sure.
Private->Public fix is fine
QDocument() constructor should probably be fixed properly but it doesnt bother  me that much since it works this way.

### CODE REVIEW

**Comment by lagner** [comment]
Hi. It's strange that it doesn't compile. For me it works like a charm. What compiler do you use? What is  the error exactly? Have you tried to do `git submodule update --init --recursive` before compiling?

Change includes it is a good suggestion definitely, but have you read README file? I use gumbo as a git submodule. And your fix breaks the existed solution. It would be great if your fix will work for both cases(git submodule and system wide installed gumbo)

As for constructor. It was implemented private by design. You don't need to invoke it manualy just use `QGumboDocument::parse("")` instead. Constructor of the QGumboNode is the same. I don't see any reasons to change it now.
Why did you do it public? What is your case? 

I'm sorry but I can't accept the request for now.

**Comment by moonshadow565** [comment]
Ofcourse i did load submodule.
Im using it directly under my project not as submodule or library.
But those include paths are clearly broken you should at least update those they probably work for you because you have gumbo installed globaly under /usr/lib

**Comment by lagner** [comment]
I have checked the project a couple minutes ago. I did the following steps
- `git clone git@github.com:lagner/QGumboParser.git`
- `cd QGumboParser/ && git submodule update --init --recursive`
- open QtCreator -> Open Project -> Select QGumboParser.pro
- build and run

As a result I have _Totals: 10 passed, 0 failed, 0 skipped, 0 blacklisted_. There are no any errors or even warnings.
I don't have system wide installed gumbo. But I checked it one more time to be completely sure

```
$:~/Projects/QGumboParser$ find /usr/lib -iname "*gumbo*"
$:~/Projects/QGumboParser$ find /usr/include/ -iname "*gumbo*"
$:~/Projects/QGumboParser$ 
```

**Comment by moonshadow565** [comment]
Its ok but by common logic thoee include shoudnt work becaue there is no file under "gumbo/gumbo.hr" but there is "gumbo-parser/src/gumbo.hr"

Look at 
qgumboparser.h and qgumboparser.cpp they clearly have wrong includes and it compiles for you with those steps because those 2 files are not present in .pro file

After adding those 2 files in .pro file
image

Cmon it isnt that hard changing those 2 includes and it will save other people from having headache!

**Comment by lagner** [comment]
Now I got it. You are right this include should be changed. I will fix it as soon as possible.
Many thanks.

**Pull request closed without merging**
